[tool.poetry]
name = "hlda"
version = "0.4"
description = "Gibbs sampler for the Hierarchical Latent Dirichlet Allocation topic model."
authors = ["Joe Wandy <joe.wandy@glasgow.ac.uk>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/joewandy/hlda"
keywords = ["topic modelling", "hierarchical lda"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = ">=3.8"
numpy = "*"
pandas = "*"
matplotlib = "*"

[tool.poetry.group.dev.dependencies]
jupyterlab = "*"
twine = "*"
pytest = "^8.4.0"

[tool.setuptools_scm]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 99
